# Generated by Django 5.0.6 on 2024-06-30 20:25

import backupss.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backupss', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Video', max_length=150)),
                ('video', models.FileField(upload_to=backupss.models.user_video_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv'])])),
                ('video_description', models.TextField(blank=True, max_length=100, null=True)),
                ('video_thumbnail', models.ImageField(upload_to=backupss.models.user_thumbnail_directory_path)),
                ('is_trashed', models.BooleanField(default=False)),
                ('trashed_at', models.DateTimeField(blank=True, null=True)),
                ('Folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='backupss.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
