# Generated by Django 5.0.6 on 2024-07-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backupss', '0003_rename_folder_videofile_folder_folder_parent_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='childfolders',
            field=models.ManyToManyField(blank=True, to='backupss.folder'),
        ),
    ]
