# Generated by Django 5.0.6 on 2024-07-14 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backupss', '0004_folder_childfolders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='childfolders',
        ),
    ]
