# Generated by Django 5.0.6 on 2024-07-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backupss', '0005_remove_folder_childfolders'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_fav',
            field=models.BooleanField(default=False),
        ),
    ]
