# Generated by Django 5.0.6 on 2025-04-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backupss', '0006_folder_is_fav'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
